# Generated by Django 3.2.6 on 2021-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_address', models.CharField(max_length=200)),
                ('seller_mob', models.CharField(max_length=10)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_address', models.CharField(max_length=200)),
                ('buyer_mob', models.CharField(max_length=10)),
            ],
        ),
    ]
