# Generated by Django 3.2.6 on 2021-08-20 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('seller_buyer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_generate.invoicemodel')),
            ],
        ),
    ]
